### ISSUE TITLE
Invalid interferograms over Armenia and Azerbaijan

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-gamma#462]
`INSAR_GAMMA` jobs rely on the Copernicus Global 30 meter public DEM (GLO-30 Public). This DEM is not available over Armenia and Azerbaijan. To lean more, visit [Digital Elevation Models](https://hyp3-docs.asf.alaska.edu/dems/#copernicus-dem) in our HyP3 documentation, or https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model

> ![cop-missing-100](https://github.com/ASFHyP3/hyp3-gamma/assets/17994518/1d81e9c0-646d-4674-97df-d9588051efc0)

Because no DEM is available in this region, `INSAR_GAMMA` jobs over Armenia and Azerbaijan produce interferograms where topographic phase has not been removed over this area:

> ![khowy](https://github.com/ASFHyP3/hyp3-gamma/assets/17994518/7e393af5-500c-43a8-ac24-28bfe1fe2ffc)

**Comment by mohseniaref** [comment]
Nothing new?

**Comment by asjohnston-asf** [comment]
No updates, unfortunately. The unavailability of these DEM tiles is documented under "Licencing and citation guidelines" at https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model ; the list of unavailable tiles is unchanged since Dec 2020. ASF is not pursuing a fix for this issue at this time.

**Comment by asjohnston-asf** [comment]
This issue is resolved in today's v6.3.4 release. The GLO-30 DEM is still not publicly available in this region, but we now use the Copernicus DEM GLO-90 to fill those gaps.

The GLO-90 dataset has a pixel spacing of 90 meters, which is not as detailed as the 30-m pixel spacing in the GLO-30 DEM, but it does allow us to provide reasonable InSAR and RTC products in this area.

**Comment by mohseniaref-InSAR** [comment]
Many many thanks 🙏 it is really good news
